table DimProduct
	lineageTag: DimProduct

	column ProductKey
		dataType: int64
		isKey
		lineageTag: ProductKey
		summarizeBy: none
		sourceColumn: ProductKey

	column SKU
		dataType: string
		lineageTag: SKU
		summarizeBy: none
		sourceColumn: SKU

	column Product
		dataType: string
		lineageTag: Product
		summarizeBy: none
		sourceColumn: Product

	column 'Standard Cost'
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: Product_StandardCost
		summarizeBy: average
		sourceColumn: Standard Cost

	column Color
		dataType: string
		lineageTag: Color
		summarizeBy: none
		sourceColumn: Color

	column 'List Price'
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ListPrice
		summarizeBy: average
		sourceColumn: List Price

	column Model
		dataType: string
		lineageTag: Model
		summarizeBy: none
		sourceColumn: Model

	column Subcategory
		dataType: string
		lineageTag: Subcategory
		summarizeBy: none
		sourceColumn: Subcategory

	column Category
		dataType: string
		lineageTag: Category
		summarizeBy: none
		sourceColumn: Category

	partition DimProduct = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("data/AdventureWorks Sales.xlsx"), null, true),
				    Product_Sheet = Source{[Item="Product_data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Product_Sheet, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers",{
				        {"ProductKey", Int64.Type},
				        {"SKU", type text},
				        {"Product", type text},
				        {"Standard Cost", type number},
				        {"Color", type text},
				        {"List Price", type number},
				        {"Model", type text},
				        {"Subcategory", type text},
				        {"Category", type text}
				    })
				in
				    #"Changed Types"

