table FactSales
	lineageTag: ac9f7ad8-a71b-4f7b-86f5-465330a9a68f

	measure 'Total Amount' = SUM(FactSales[Amount])
		formatString: #,0.00
		lineageTag: f01eba9b-4cad-4ac1-afdb-52e1e7ba1783

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6a937f25-ef85-4ff6-a10b-ecf58be2337d
		summarizeBy: none
		sourceColumn: OrderDate

		annotation UnderlyingDateTimeDataType = Date

	column Amount
		dataType: double
		lineageTag: af17cda1-8fb6-4cdc-9791-715117c6bcfc
		sourceColumn: Amount

	partition FactSales = m
		mode: import
		source =
				let
				    // ── Real data source ───────────────────────────────────────────────
				    // A PBIP whose only query is #table(...) has NO data source at all.
				    // Power BI Desktop then NREs in MashupDiscoveryService while probing
				    // for composite-model consent on open, and silently degrades every
				    // derived column's dataType to string. Anchoring to the CSV keeps a
				    // genuine source in the model while staying self-contained.
				    Source = Csv.Document(
				        File.Contents(BasePath & "samples/pbip-calendar-baseline/data/FactSales.csv"),
				        [Delimiter = ",", Columns = 2, Encoding = 65001]
				    ),
				    Typed = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Result = Table.TransformColumnTypes(Typed, {
				        {"OrderDate", type date},
				        {"Amount", type number}
				    })
				in
				    Result

	annotation PBI_ResultType = Table

